IOTCENTRAL_DEVICE_SECURITY_TYPE=DPS
IOTCENTRAL_DEVICE_ID=evsecert-0000000000af1ec3-0000
IOTCENTRAL_SCOPE_ID=0ne009C0405
IOTCENTRAL_CERT_ID=0x83000002
IOTCENTRAL_KEY_ID=0x83000001
IOTCENTRAL_MODEL_ID="dtmi:nxp:nxp;1"
IOTCENTRAL_DEVICE_HUB_URI=CS
